making a small change to avoid a confusion.
facebookresearch/llama pull request #754
Opened 2023-09-02 22:24 UTC by JaredLevi18

Approaching issue #658

2023-09-03 14:15 UTC, jspisak requested changes
Thanks for adding this comment. I agree it can be confusing without some code comments. How about:

# Note that self.params.max_seq_len  is multiplied by 2 because the token limit for the Llama 2 generation of models is 4096. Adding this multiplier instead of using 4096 directly allows for dynamism of token lengths while training or fine-tuning.

2023-09-03 16:16 UTC, JaredLevi18 commented
Hahaha, that's even better, didn't think of it like that, thanks.

2023-09-03 18:06 UTC, Truewarlock approved these changes

2023-09-03 18:11 UTC, merged

2024-05-20 18:42 UTC, JaredLevi18 commented
> > Thanks for adding this comment. I agree it can be confusing without some code comments. How about:
> > # Note that self.params.max_seq_len is multiplied by 2 because the token limit for the Llama 2 generation of models is 4096. Adding this multiplier instead of using 4096 directly allows for dynamism of token lengths while training or fine-tuning.
> 
> Sorry, I am still confused with the question. So the the maxximum number of tokens that is supported by llama 1 is 2048 or 4096? @jspisak

Is 4096 the total.