Add parameter substitution to `download.sh`
facebookresearch/llama pull request #8
Opened 2023-02-24 21:48 UTC by christopherwoodall

Utilize parameter expansion in `download.sh` to allow both `PRESIGNED_URL` and `TARGET_FOLDER` to be assigned via environmental variables.

2023-08-31 19:45 UTC, ckxng commented
picking this up, I am reviewing several of the outstanding PRs for download.sh

2023-08-31 19:47 UTC, ckxng commented
@TheFinalJoke take a look at this

2023-09-06 17:07 UTC, ckxng commented
The user-friendliness of prompting for the signed URL is nice, but I also see the value in accepting ENV vars.  I would be interested to see a diff that preserves both behaviors.  (Prompt if ENV var not set?)

2023-09-06 18:21 UTC, ckxng commented
Very good, I think this one should merge before #441, so that this behavior is in place before [krrishnarraj](https://github.com/krrishnarraj) syncs with main.

2023-09-06 19:15 UTC, samuelselvan approved these changes
This looks good to me. @ruanslv any thoughts?

2023-09-06 20:03 UTC, ruanslv requested changes
Seems like there's a merge conflict?

2023-09-06 20:03 UTC, ruanslv commented on README.md
> +
Most of this feel redundant to me. I suggest instead to just add a example below:

"Then to run the script: `./download.sh`. There are optional ENV variables that can be used for automation.

"Then run the download.sh script, passing the URL provided when prompted to start the download (or using the )".

```suggestion
```

2023-09-06 20:34 UTC, christopherwoodall commented on download.sh
> -echo ""
Depending on the console size the second `read` can make the terminal look "messy"(116 characters long).

2023-09-07 01:32 UTC, ruanslv commented
Doesn't look like merge with latest main branch worked, I still see conflicting files.

If you want some help on this I'd need write access to your fork

2023-09-07 12:15 UTC, closed without merging

2023-09-08 10:57 UTC, christopherwoodall commented
Thank you @ruanslv, but I am afraid I no longer have cycles to put toward this commit. I believe #290 may cover the same use case, and with it being newer, take less time to catch up.